export * from "./header/Header";
export * from "./search/SearchResults";
export * from "./footer/Footer";
export * from "./hoc/ContentWrap";
export * from "./lazyLoadImg/LazyLoadImg";
export * from "./switchTabs/SwitchTabs";
export * from "./carousel/Carousel";
export * from "./rating/Rating";
export * from "./genres/Genres";
